import { ListData } from './ListData';

export class ListDataViewModel {
  getListDataList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
  }

  getFeaturedRecommendationsList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('The Story Of The Wind And I','曹操',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
  }

  getRecentlyPlayedList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('0','',[],''));
    ListDataList.push(new ListData('The Story Of The Wind And I','曹操',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));

    return ListDataList;
  }


  getPopularList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('1','',[],''));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
  }
  getHisMoreList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('','',[],''));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
    return ListDataList;
  }

  getNewReleasesList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('2','',[],''));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
  }

  getRecommendList(): ListData[] {
    let ListDataList: Array<ListData> = [];
    ListDataList.push(new ListData('3','',[],''));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('The Story Of The Wind And I','The Story Of The Wind And I',['Ado', '周杰伦'],'app.media.wind_and_I'));
    ListDataList.push(new ListData('铃芽之旅', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅1', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅2', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅3', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    ListDataList.push(new ListData('铃芽之旅4', 'Suzume(feat.Toaka)', ['RADWIMPS'], 'app.media.gaomu'));
    return ListDataList;
  }


}
